### PR TITLE
Update index.js - fixed for instagram change

### LINKED ISSUE #9: Social ghost only works partially
Hey there,

the issue is that the add-on only works when you view the stories from the top on the main page. However, if you search for a user and view the story from the search results or directly from their profile, you will still be shown as seen.

Regards

### PR DESCRIPTION
**Pull request by halilnevzat**
instagram changed parameter name so i added that also ; PolarisStoriesV3SeenMutation

### CODE REVIEW

**Comment by nhymxu** [comment]
Hi @halilnevzat 
Thanks for your support. Can you explain what instagram screen using `PolarisStoriesV3SeenMutation`?
Is this same as #9 report 🤔

**Comment by nhymxu** [comment]
Hmm, this show when 
— Search user
— on search result page, click story

**Review by nhymxu — APPROVED** [review]
LGTM

Thanks for your support 💯

**Comment by halilnevzat** [comment]
> Hmm, this show when — Search user — on search result page, click story

its in a user profile page of someone that i want to see story, for example; 
https://www.instagram.com/hamakligezgin

**Pull request merged**
